# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 983c2f29e495abafd7549b4f24aa2c6f70a4df1254c7951389bf0186d4bfdefc50498d310255745be69911b9a772b5a584f624886f91637c0f883bbbda3679c8

test:
  secret_key_base: 1b41feeeee837f78eca86abe4cca9e4667debdd106fda783b1b41a40aa3f7521f4d4a10678fd3458fb0b6681b82b8e32d0af3159ac34b16592f0ab8f19dedf13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
